### ISSUE TITLE
Error in running

### ISSUE THREAD

**Issue by brijyot** [hprobotic/teamtreehouse-downloader#2]
What version of node is compatible

I get following errors on running with node app.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'sanitize-filename'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (J:\teamtreehouse\download.js:7:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
PS J:\teamtreehouse>

**Comment by hprobotic** [comment]
Hi @brijyot 
I just update the `package.json` to add missing `sanitize-filename` package
Thanks

**Comment by hprobotic** [comment]
You can run node app.js instead of nodemon
